name: Pipeline

on: [push]
env: 
   APPLICATION_NAME: python-notebook
   REGISTRY : "https://hub.docker.com/repository/docker/adityareddy369/pythondemo"
   REGISTRY_CREDENTIAL : ${{secrets.DOCKER_USERNAME}} &&  ${{secrets.DOCKER_PASSWORD}}
jobs:
  lint:
    runs-on : ubuntu-18.04
    steps:
    -  uses: actions/checkout@v1
    -  name: Setup Python Env
       uses: actions/setup-python@v2
    -  name: Install requirements
       run: pip install  --quiet --requirement requirement.txt
    -  name: Lint code
       run: |
         flake8  
    -  name: Run unit tests
       run: |
         python - m unitest  --verbose --failfast
